# Generated by Django 4.2 on 2023-04-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='active',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(choices=[('main_menu', 'Main Menu'), ('footer_menu', 'Footer Menu')], default='main_menu', max_length=20),
        ),
    ]
